# drawn from https://forum.gitlab.com/t/running-karma-tests-with-chrome-and-gitlab-ci/14476

stages:
  - test
  - dependency_scanning

test:
  image: weltn24/up-docker-node-chrome-headless:latest
  stage: test
  cache:
    paths:
      - node_modules/
  tags:
    - linux
  # remove node 10 and install node 8.9 because that's what angular wants
  before_script:
    - apt-get purge --auto-remove nodejs -y
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - apt-get install -y nodejs
    - yarn install
  script:
    - yarn test --watch=false --code-coverage=false

dependency_scanning:
  image: docker:stable
  stage: dependency_scanning
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
      --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
      --volume "$PWD:/code"
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
