image: weltn24/up-docker-node-chrome-headless:latest

before_script:
  - yarn install

cache:
  paths:
  - node_modules/

stages:
  - test

test:
  stage: test
  tags:
    - linux
  before_script:
    - apt-get purge --auto-remove nodejs -y
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - apt-get install -y nodejs
  script:
    - ./node_modules/.bin/ng test --watch=false --code-coverage=true --single-run=true --browser=ChromeHeadless
  artifacts:
    paths:
      - coverage/*
  coverage: '/(\d*.?\d+)%/'