stages:
  - build
  - test

build:
  image: node:12.16.3-alpine
  stage: build
  cache:
    untracked: true
  script:
    - apk add yarn
    - yarn install

test:
  image: node:12.16.3-alpine
  stage: test
  cache:
    untracked: true
    policy: pull
  script:
    - yarn test --ci
