image: weltn24/up-docker-node-chrome-headless:latest

before_script:
  - yarn install

cache:
  paths:
  - node_modules/

stages:
  - test

test:
  stage: test
  tags:
    - linux
  script:
    - ./node_modules/.bin/ng test --watch=false --code-coverage=true --single-run=true --browser=ChromeHeadless
  artifacts:
    paths:
      - coverage/*
  coverage: '/(\d*.?\d+)%/