# drawn from https://forum.gitlab.com/t/running-karma-tests-with-chrome-and-gitlab-ci/14476

image: weltn24/up-docker-node-chrome-headless:latest

# remove node 10 and install node 8.9 because that's what angular wants
before_script:
  - apt-get purge --auto-remove nodejs -y
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt-get install -y nodejs
  - yarn install

cache:
  paths:
  - node_modules/

stages:
  - test

test:
  stage: test
  tags:
    - linux
  script:
    - yarn test --watch=false --code-coverage=false
